version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
 
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://your_user:your_password@postgres:5432/your_database
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      REACT_APP_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend